<!DOCTYPE html>
<html lang="en" ng-app="learnerApp">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="E-Leaner Website">
  <meta name="author" content="Spider">
    <meta name="<?php echo $CSRF_NAME; ?>" value="<?php echo $CSRF_VALUE; ?>">
  <base href="/" target="_blank">
  <title>E-Leaner <?php echo $title; ?> {{title}}</title>
  <link rel="icon" href="favicon.ico" type="image/ico">

  <!-- bower:css -->
  <link rel="stylesheet" href="/client/dependencies/toastr/toastr.css" />
  <!-- endbower -->
  <link rel="stylesheet" href="/app/all.css" />

</head>
<body>
  <spider-navbar title="Adele's E-Leaner"></spider-navbar>
  <div ui-view></div>
  <footer class="container-fluid text-center">
    E-Leaner 2015
  </footer>
  <script>
      window.CurrentBootstrappedUser =<?php echo json_encode($BOOTSTRAPUSER); ?>;
  </script>
  <!-- bower:js -->
  <script src="/client/dependencies/jquery/dist/jquery.js"></script>
  <script src="/client/dependencies/toastr/toastr.js"></script>
  <script src="/client/dependencies/moment/moment.js"></script>
  <script src="/client/dependencies/lodash/lodash.js"></script>
  <script src="/client/dependencies/bootstrap-sass/assets/javascripts/bootstrap.js"></script>
  <script src="/client/dependencies/angular/angular.js"></script>
  <script src="/client/dependencies/angular-ui-router/release/angular-ui-router.js"></script>
  <script src="/client/dependencies/angular-animate/angular-animate.js"></script>
  <script src="/client/dependencies/angular-aria/angular-aria.js"></script>
  <script src="/client/dependencies/angular-cookies/angular-cookies.js"></script>
  <script src="/client/dependencies/angular-messages/angular-messages.js"></script>
  <script src="/client/dependencies/angular-resource/angular-resource.js"></script>
  <script src="/client/dependencies/angular-sanitize/angular-sanitize.js"></script>
  <script src="/client/dependencies/angular-touch/angular-touch.js"></script>
  <script src="/client/dependencies/angular-socket-io/socket.js"></script>
  <script src="/client/dependencies/angular-local-storage/dist/angular-local-storage.js"></script>
  <script src="/client/dependencies/angular-bootstrap/ui-bootstrap-tpls.js"></script>
  <!-- endbower -->
  <script src="/js/all.js"></script>

  <!-- Google Analytics: change UA-XXXXX-X to be your site's ID -->
  <script>
  !function(A,n,g,u,l,a,r){A.GoogleAnalyticsObject=l,A[l]=A[l]||function(){
    (A[l].q=A[l].q||[]).push(arguments)},A[l].l=+new Date,a=n.createElement(g),
    r=n.getElementsByTagName(g)[0],a.src=u,r.parentNode.insertBefore(a,r)
  }(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-XXXXX-X');
  ga('send', 'pageview');
  </script>

</body>
</html>
